### ISSUE TITLE
Export is not working

### ISSUE THREAD

**Issue by daviddelon** [open-craft/opencraft#195] opened 2017-04-08 11:13 UTC
Course : https://studio-mavoix.opencraft.hosting/course/course-v1:MAVOIX+MV03+2017_Session1 , 

Hello,
When I try to export a course, from Open edX Studio, Tools / Export / Export Course Content , the following message is displayed : 

The Studio servers encountered an error
An error occurred in Studio and the page could not be loaded. Please try again in a few moments. "We've logged the error and our staff is currently working to resolve this error as soon as possible. If the problem persists, please email us at contact@xxxxxxxxx.xxxx

And no export file is created.

**Comment by bradenmacdonald** [comment] 2017-04-08 18:26
Thanks for reporting this @daviddelon. We will investigate.

**Comment by bradenmacdonald** [comment] 2017-04-10 23:36
@daviddelon We investigated this issue, and it appears to be caused by non-ASCII characters in the filename of files that are uploaded in Studio's "Files & Uploads" section. Usually this is caused by accented letters like é, è, à, etc. You should be able to fix this yourself by finding any such letters in the Studio Uploads page, and then deleting and re-uploading the file with a file name that does not contain accented letters.

This is a known bug with the edX platform that has been around for a while. If you'd like us to help you update your files, we can do that as a support task at our usual hourly support rate; we can also investigate and fix this issue for you if you're willing to sponsor that bugfix for the edx-platform.

**Comment by antoviaque** [comment] 2017-04-27 17:51
Closing as this is an upstream issue.

**Closed by antoviaque** 2017-04-27 17:51 UTC
